# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_mlx_from_numeric <- function(x_, dim_, dtype_, device_) {
    .Call(`_Rmlx_cpp_mlx_from_numeric`, x_, dim_, dtype_, device_)
}

cpp_mlx_empty <- function(dim_, dtype_, device_) {
    .Call(`_Rmlx_cpp_mlx_empty`, dim_, dtype_, device_)
}

cpp_mlx_to_r <- function(xp_) {
    .Call(`_Rmlx_cpp_mlx_to_r`, xp_)
}

cpp_mlx_eval <- function(xp_) {
    invisible(.Call(`_Rmlx_cpp_mlx_eval`, xp_))
}

cpp_mlx_shape <- function(xp_) {
    .Call(`_Rmlx_cpp_mlx_shape`, xp_)
}

cpp_mlx_dtype <- function(xp_) {
    .Call(`_Rmlx_cpp_mlx_dtype`, xp_)
}

cpp_mlx_unary <- function(xp_, op) {
    .Call(`_Rmlx_cpp_mlx_unary`, xp_, op)
}

cpp_mlx_binary <- function(xp1_, xp2_, op, dtype_str, device_str) {
    .Call(`_Rmlx_cpp_mlx_binary`, xp1_, xp2_, op, dtype_str, device_str)
}

cpp_mlx_reduce <- function(xp_, op) {
    .Call(`_Rmlx_cpp_mlx_reduce`, xp_, op)
}

cpp_mlx_reduce_axis <- function(xp_, op, axis, keepdims) {
    .Call(`_Rmlx_cpp_mlx_reduce_axis`, xp_, op, axis, keepdims)
}

cpp_mlx_transpose <- function(xp_) {
    .Call(`_Rmlx_cpp_mlx_transpose`, xp_)
}

cpp_mlx_reshape <- function(xp_, new_dim_) {
    .Call(`_Rmlx_cpp_mlx_reshape`, xp_, new_dim_)
}

cpp_mlx_matmul <- function(xp1_, xp2_, dtype_str, device_str) {
    .Call(`_Rmlx_cpp_mlx_matmul`, xp1_, xp2_, dtype_str, device_str)
}

cpp_mlx_synchronize <- function(device_str) {
    invisible(.Call(`_Rmlx_cpp_mlx_synchronize`, device_str))
}

cpp_mlx_slice <- function(xp_, starts_, stops_, strides_) {
    .Call(`_Rmlx_cpp_mlx_slice`, xp_, starts_, stops_, strides_)
}

cpp_mlx_cumulative <- function(xp_, op) {
    .Call(`_Rmlx_cpp_mlx_cumulative`, xp_, op)
}

cpp_mlx_solve <- function(a_xp_, b_xp_, dtype_str, device_str) {
    .Call(`_Rmlx_cpp_mlx_solve`, a_xp_, b_xp_, dtype_str, device_str)
}

