# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_mlx_value_grad <- function(fun_sexp, args, argnums, return_value) {
    .Call(`_Rmlx_cpp_mlx_value_grad`, fun_sexp, args, argnums, return_value)
}

cpp_mlx_stop_gradient <- function(xp_) {
    .Call(`_Rmlx_cpp_mlx_stop_gradient`, xp_)
}

cpp_mlx_from_r <- function(x_, dim_, dtype_, device_) {
    .Call(`_Rmlx_cpp_mlx_from_r`, x_, dim_, dtype_, device_)
}

cpp_mlx_empty <- function(dim_, dtype_, device_) {
    .Call(`_Rmlx_cpp_mlx_empty`, dim_, dtype_, device_)
}

cpp_mlx_to_r <- function(xp_) {
    .Call(`_Rmlx_cpp_mlx_to_r`, xp_)
}

cpp_mlx_eval <- function(xp_) {
    invisible(.Call(`_Rmlx_cpp_mlx_eval`, xp_))
}

cpp_mlx_shape <- function(xp_) {
    .Call(`_Rmlx_cpp_mlx_shape`, xp_)
}

cpp_mlx_dtype <- function(xp_) {
    .Call(`_Rmlx_cpp_mlx_dtype`, xp_)
}

cpp_mlx_unary <- function(xp_, op) {
    .Call(`_Rmlx_cpp_mlx_unary`, xp_, op)
}

cpp_mlx_binary <- function(xp1_, xp2_, op, dtype_str, device_str) {
    .Call(`_Rmlx_cpp_mlx_binary`, xp1_, xp2_, op, dtype_str, device_str)
}

cpp_mlx_reduce <- function(xp_, op) {
    .Call(`_Rmlx_cpp_mlx_reduce`, xp_, op)
}

cpp_mlx_reduce_axis <- function(xp_, op, axis, keepdims) {
    .Call(`_Rmlx_cpp_mlx_reduce_axis`, xp_, op, axis, keepdims)
}

cpp_mlx_transpose <- function(xp_) {
    .Call(`_Rmlx_cpp_mlx_transpose`, xp_)
}

cpp_mlx_reshape <- function(xp_, new_dim_) {
    .Call(`_Rmlx_cpp_mlx_reshape`, xp_, new_dim_)
}

cpp_mlx_matmul <- function(xp1_, xp2_, dtype_str, device_str) {
    .Call(`_Rmlx_cpp_mlx_matmul`, xp1_, xp2_, dtype_str, device_str)
}

cpp_mlx_random_normal <- function(dim_, mean, std, dtype_str, device_str) {
    .Call(`_Rmlx_cpp_mlx_random_normal`, dim_, mean, std, dtype_str, device_str)
}

cpp_mlx_random_bernoulli <- function(dim_, prob, device_str) {
    .Call(`_Rmlx_cpp_mlx_random_bernoulli`, dim_, prob, device_str)
}

cpp_mlx_concat <- function(args_, axis) {
    .Call(`_Rmlx_cpp_mlx_concat`, args_, axis)
}

cpp_mlx_random_uniform <- function(dim_, low, high, dtype_str, device_str) {
    .Call(`_Rmlx_cpp_mlx_random_uniform`, dim_, low, high, dtype_str, device_str)
}

cpp_mlx_synchronize <- function(device_str) {
    invisible(.Call(`_Rmlx_cpp_mlx_synchronize`, device_str))
}

cpp_mlx_slice <- function(xp_, starts_, stops_, strides_) {
    .Call(`_Rmlx_cpp_mlx_slice`, xp_, starts_, stops_, strides_)
}

cpp_mlx_cumulative <- function(xp_, op) {
    .Call(`_Rmlx_cpp_mlx_cumulative`, xp_, op)
}

cpp_mlx_solve <- function(a_xp_, b_xp_, dtype_str, device_str) {
    .Call(`_Rmlx_cpp_mlx_solve`, a_xp_, b_xp_, dtype_str, device_str)
}

cpp_mlx_fft <- function(xp_, inverse, device_str) {
    .Call(`_Rmlx_cpp_mlx_fft`, xp_, inverse, device_str)
}

cpp_mlx_cholesky <- function(a_xp_, upper, dtype_str, device_str) {
    .Call(`_Rmlx_cpp_mlx_cholesky`, a_xp_, upper, dtype_str, device_str)
}

cpp_mlx_qr <- function(a_xp_, dtype_str, device_str) {
    .Call(`_Rmlx_cpp_mlx_qr`, a_xp_, dtype_str, device_str)
}

cpp_mlx_svd <- function(a_xp_, compute_uv, dtype_str, device_str) {
    .Call(`_Rmlx_cpp_mlx_svd`, a_xp_, compute_uv, dtype_str, device_str)
}

cpp_mlx_pinv <- function(a_xp_, dtype_str, device_str) {
    .Call(`_Rmlx_cpp_mlx_pinv`, a_xp_, dtype_str, device_str)
}

