# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_mlx_zeros <- function(dim_, dtype_str, device_str) {
    .Call(`_Rmlx_cpp_mlx_zeros`, dim_, dtype_str, device_str)
}

cpp_mlx_ones <- function(dim_, dtype_str, device_str) {
    .Call(`_Rmlx_cpp_mlx_ones`, dim_, dtype_str, device_str)
}

cpp_mlx_zeros_like <- function(xp_, dtype_str, device_str) {
    .Call(`_Rmlx_cpp_mlx_zeros_like`, xp_, dtype_str, device_str)
}

cpp_mlx_ones_like <- function(xp_, dtype_str, device_str) {
    .Call(`_Rmlx_cpp_mlx_ones_like`, xp_, dtype_str, device_str)
}

cpp_mlx_full <- function(dim_, value_, dtype_str, device_str) {
    .Call(`_Rmlx_cpp_mlx_full`, dim_, value_, dtype_str, device_str)
}

cpp_mlx_eye <- function(n, m, k, dtype_str, device_str) {
    .Call(`_Rmlx_cpp_mlx_eye`, n, m, k, dtype_str, device_str)
}

cpp_mlx_tri <- function(n, m, k, dtype_str, device_str) {
    .Call(`_Rmlx_cpp_mlx_tri`, n, m, k, dtype_str, device_str)
}

cpp_mlx_identity <- function(n, dtype_str, device_str) {
    .Call(`_Rmlx_cpp_mlx_identity`, n, dtype_str, device_str)
}

cpp_mlx_arange <- function(start_, stop, step_, dtype_str, device_str) {
    .Call(`_Rmlx_cpp_mlx_arange`, start_, stop, step_, dtype_str, device_str)
}

cpp_mlx_linspace <- function(start, stop, num, dtype_str, device_str) {
    .Call(`_Rmlx_cpp_mlx_linspace`, start, stop, num, dtype_str, device_str)
}

cpp_mlx_value_grad <- function(fun_sexp, args, argnums, return_value) {
    .Call(`_Rmlx_cpp_mlx_value_grad`, fun_sexp, args, argnums, return_value)
}

cpp_mlx_stop_gradient <- function(xp_) {
    .Call(`_Rmlx_cpp_mlx_stop_gradient`, xp_)
}

cpp_mlx_from_r <- function(x_, dim_, dtype_, device_) {
    .Call(`_Rmlx_cpp_mlx_from_r`, x_, dim_, dtype_, device_)
}

cpp_mlx_empty <- function(dim_, dtype_, device_) {
    .Call(`_Rmlx_cpp_mlx_empty`, dim_, dtype_, device_)
}

cpp_mlx_to_r <- function(xp_) {
    .Call(`_Rmlx_cpp_mlx_to_r`, xp_)
}

cpp_mlx_eval <- function(xp_) {
    invisible(.Call(`_Rmlx_cpp_mlx_eval`, xp_))
}

cpp_mlx_shape <- function(xp_) {
    .Call(`_Rmlx_cpp_mlx_shape`, xp_)
}

cpp_mlx_dtype <- function(xp_) {
    .Call(`_Rmlx_cpp_mlx_dtype`, xp_)
}

cpp_mlx_compile_create <- function(fun_sexp, shapeless) {
    .Call(`_Rmlx_cpp_mlx_compile_create`, fun_sexp, shapeless)
}

cpp_mlx_compile_call <- function(compiled_xp, mlx_args) {
    .Call(`_Rmlx_cpp_mlx_compile_call`, compiled_xp, mlx_args)
}

cpp_mlx_disable_compile <- function() {
    invisible(.Call(`_Rmlx_cpp_mlx_disable_compile`))
}

cpp_mlx_enable_compile <- function() {
    invisible(.Call(`_Rmlx_cpp_mlx_enable_compile`))
}

cpp_mlx_default_device <- function() {
    .Call(`_Rmlx_cpp_mlx_default_device`)
}

cpp_mlx_set_default_device <- function(device_str) {
    invisible(.Call(`_Rmlx_cpp_mlx_set_default_device`, device_str))
}

cpp_mlx_import_function <- function(path) {
    .Call(`_Rmlx_cpp_mlx_import_function`, path)
}

cpp_mlx_call_imported <- function(fn_xp, args_ptrs, kwargs_ptrs, device_str) {
    .Call(`_Rmlx_cpp_mlx_call_imported`, fn_xp, args_ptrs, kwargs_ptrs, device_str)
}

cpp_mlx_where <- function(cond_xp_, xp_true_, xp_false_, dtype_str, device_str) {
    .Call(`_Rmlx_cpp_mlx_where`, cond_xp_, xp_true_, xp_false_, dtype_str, device_str)
}

cpp_mlx_take <- function(xp_, indices_, axis) {
    .Call(`_Rmlx_cpp_mlx_take`, xp_, indices_, axis)
}

cpp_mlx_slice <- function(xp_, starts_, stops_, strides_) {
    .Call(`_Rmlx_cpp_mlx_slice`, xp_, starts_, stops_, strides_)
}

cpp_mlx_slice_update <- function(xp_, update_xp_, start_, stop_, strides_) {
    .Call(`_Rmlx_cpp_mlx_slice_update`, xp_, update_xp_, start_, stop_, strides_)
}

cpp_mlx_gather <- function(xp_, indices_, axes_, device_str) {
    .Call(`_Rmlx_cpp_mlx_gather`, xp_, indices_, axes_, device_str)
}

cpp_mlx_scatter <- function(xp_, indices_xp_, updates_xp_, axis) {
    .Call(`_Rmlx_cpp_mlx_scatter`, xp_, indices_xp_, updates_xp_, axis)
}

cpp_mlx_assign <- function(xp_, normalized_, updates_flat_xp_, dim_sizes_) {
    .Call(`_Rmlx_cpp_mlx_assign`, xp_, normalized_, updates_flat_xp_, dim_sizes_)
}

cpp_mlx_masked_scatter <- function(xp_, mask_xp_, updates_xp_, device_str) {
    .Call(`_Rmlx_cpp_mlx_masked_scatter`, xp_, mask_xp_, updates_xp_, device_str)
}

cpp_mlx_save <- function(xp_, file) {
    invisible(.Call(`_Rmlx_cpp_mlx_save`, xp_, file))
}

cpp_mlx_load <- function(file, device_str) {
    .Call(`_Rmlx_cpp_mlx_load`, file, device_str)
}

cpp_mlx_save_safetensors <- function(array_ptrs, array_names, metadata_names, metadata_values, file) {
    invisible(.Call(`_Rmlx_cpp_mlx_save_safetensors`, array_ptrs, array_names, metadata_names, metadata_values, file))
}

cpp_mlx_load_safetensors <- function(file, device_str) {
    .Call(`_Rmlx_cpp_mlx_load_safetensors`, file, device_str)
}

cpp_mlx_save_gguf <- function(array_ptrs, array_names, metadata_payload, metadata_names, file) {
    invisible(.Call(`_Rmlx_cpp_mlx_save_gguf`, array_ptrs, array_names, metadata_payload, metadata_names, file))
}

cpp_mlx_load_gguf <- function(file, device_str) {
    .Call(`_Rmlx_cpp_mlx_load_gguf`, file, device_str)
}

cpp_mlx_solve <- function(a_xp_, b_xp_, dtype_str, device_str) {
    .Call(`_Rmlx_cpp_mlx_solve`, a_xp_, b_xp_, dtype_str, device_str)
}

cpp_mlx_cholesky <- function(a_xp_, upper, dtype_str, device_str) {
    .Call(`_Rmlx_cpp_mlx_cholesky`, a_xp_, upper, dtype_str, device_str)
}

cpp_mlx_qr <- function(a_xp_, dtype_str, device_str) {
    .Call(`_Rmlx_cpp_mlx_qr`, a_xp_, dtype_str, device_str)
}

cpp_mlx_svd <- function(a_xp_, compute_uv, dtype_str, device_str) {
    .Call(`_Rmlx_cpp_mlx_svd`, a_xp_, compute_uv, dtype_str, device_str)
}

cpp_mlx_pinv <- function(a_xp_, dtype_str, device_str) {
    .Call(`_Rmlx_cpp_mlx_pinv`, a_xp_, dtype_str, device_str)
}

cpp_mlx_norm <- function(xp_, ord_, axes, keepdims, device_str) {
    .Call(`_Rmlx_cpp_mlx_norm`, xp_, ord_, axes, keepdims, device_str)
}

cpp_mlx_eig <- function(xp_, device_str) {
    .Call(`_Rmlx_cpp_mlx_eig`, xp_, device_str)
}

cpp_mlx_eigvals <- function(xp_, device_str) {
    .Call(`_Rmlx_cpp_mlx_eigvals`, xp_, device_str)
}

cpp_mlx_eigvalsh <- function(xp_, uplo, device_str) {
    .Call(`_Rmlx_cpp_mlx_eigvalsh`, xp_, uplo, device_str)
}

cpp_mlx_eigh <- function(xp_, uplo, device_str) {
    .Call(`_Rmlx_cpp_mlx_eigh`, xp_, uplo, device_str)
}

cpp_mlx_solve_triangular <- function(a_xp_, b_xp_, upper, device_str) {
    .Call(`_Rmlx_cpp_mlx_solve_triangular`, a_xp_, b_xp_, upper, device_str)
}

cpp_mlx_cross <- function(a_xp_, b_xp_, axis, device_str) {
    .Call(`_Rmlx_cpp_mlx_cross`, a_xp_, b_xp_, axis, device_str)
}

cpp_mlx_trace <- function(a_xp_, offset, axis1, axis2, device_str) {
    .Call(`_Rmlx_cpp_mlx_trace`, a_xp_, offset, axis1, axis2, device_str)
}

cpp_mlx_diagonal <- function(a_xp_, offset, axis1, axis2, device_str) {
    .Call(`_Rmlx_cpp_mlx_diagonal`, a_xp_, offset, axis1, axis2, device_str)
}

cpp_mlx_diag <- function(a_xp_, k, device_str) {
    .Call(`_Rmlx_cpp_mlx_diag`, a_xp_, k, device_str)
}

cpp_mlx_outer <- function(a_xp_, b_xp_, device_str) {
    .Call(`_Rmlx_cpp_mlx_outer`, a_xp_, b_xp_, device_str)
}

cpp_mlx_inv <- function(a_xp_, device_str) {
    .Call(`_Rmlx_cpp_mlx_inv`, a_xp_, device_str)
}

cpp_mlx_tri_inv <- function(a_xp_, upper, device_str) {
    .Call(`_Rmlx_cpp_mlx_tri_inv`, a_xp_, upper, device_str)
}

cpp_mlx_cholesky_inv <- function(a_xp_, upper, device_str) {
    .Call(`_Rmlx_cpp_mlx_cholesky_inv`, a_xp_, upper, device_str)
}

cpp_mlx_lu <- function(a_xp_, device_str) {
    .Call(`_Rmlx_cpp_mlx_lu`, a_xp_, device_str)
}

cpp_mlx_kron <- function(a_xp_, b_xp_, device_str) {
    .Call(`_Rmlx_cpp_mlx_kron`, a_xp_, b_xp_, device_str)
}

cpp_mlx_unary <- function(xp_, op) {
    .Call(`_Rmlx_cpp_mlx_unary`, xp_, op)
}

cpp_mlx_logical_not <- function(xp_) {
    .Call(`_Rmlx_cpp_mlx_logical_not`, xp_)
}

cpp_mlx_binary <- function(xp1_, xp2_, op, dtype_str, device_str) {
    .Call(`_Rmlx_cpp_mlx_binary`, xp1_, xp2_, op, dtype_str, device_str)
}

cpp_mlx_minimum <- function(xp1_, xp2_, device_str) {
    .Call(`_Rmlx_cpp_mlx_minimum`, xp1_, xp2_, device_str)
}

cpp_mlx_maximum <- function(xp1_, xp2_, device_str) {
    .Call(`_Rmlx_cpp_mlx_maximum`, xp1_, xp2_, device_str)
}

cpp_mlx_clip <- function(xp_, min_, max_, device_str) {
    .Call(`_Rmlx_cpp_mlx_clip`, xp_, min_, max_, device_str)
}

cpp_mlx_floor_divide <- function(xp1_, xp2_, device_str) {
    .Call(`_Rmlx_cpp_mlx_floor_divide`, xp1_, xp2_, device_str)
}

cpp_mlx_remainder <- function(xp1_, xp2_, device_str) {
    .Call(`_Rmlx_cpp_mlx_remainder`, xp1_, xp2_, device_str)
}

cpp_mlx_logical <- function(xp1_, xp2_, op, device_str) {
    .Call(`_Rmlx_cpp_mlx_logical`, xp1_, xp2_, op, device_str)
}

cpp_mlx_isclose <- function(xp1_, xp2_, rtol, atol, equal_nan, device_str) {
    .Call(`_Rmlx_cpp_mlx_isclose`, xp1_, xp2_, rtol, atol, equal_nan, device_str)
}

cpp_mlx_allclose <- function(xp1_, xp2_, rtol, atol, equal_nan, device_str) {
    .Call(`_Rmlx_cpp_mlx_allclose`, xp1_, xp2_, rtol, atol, equal_nan, device_str)
}

cpp_mlx_nan_to_num <- function(xp_, nan_, posinf_, neginf_) {
    .Call(`_Rmlx_cpp_mlx_nan_to_num`, xp_, nan_, posinf_, neginf_)
}

cpp_mlx_conv1d <- function(input_xp_, weight_xp_, stride, padding, dilation, groups, device_str) {
    .Call(`_Rmlx_cpp_mlx_conv1d`, input_xp_, weight_xp_, stride, padding, dilation, groups, device_str)
}

cpp_mlx_conv2d <- function(input_xp_, weight_xp_, stride, padding, dilation, groups, device_str) {
    .Call(`_Rmlx_cpp_mlx_conv2d`, input_xp_, weight_xp_, stride, padding, dilation, groups, device_str)
}

cpp_mlx_conv3d <- function(input_xp_, weight_xp_, stride, padding, dilation, groups, device_str) {
    .Call(`_Rmlx_cpp_mlx_conv3d`, input_xp_, weight_xp_, stride, padding, dilation, groups, device_str)
}

cpp_mlx_conv_transpose1d <- function(input_xp_, weight_xp_, stride, padding, dilation, output_padding, groups, device_str) {
    .Call(`_Rmlx_cpp_mlx_conv_transpose1d`, input_xp_, weight_xp_, stride, padding, dilation, output_padding, groups, device_str)
}

cpp_mlx_conv_transpose2d <- function(input_xp_, weight_xp_, stride, padding, dilation, output_padding, groups, device_str) {
    .Call(`_Rmlx_cpp_mlx_conv_transpose2d`, input_xp_, weight_xp_, stride, padding, dilation, output_padding, groups, device_str)
}

cpp_mlx_conv_transpose3d <- function(input_xp_, weight_xp_, stride, padding, dilation, output_padding, groups, device_str) {
    .Call(`_Rmlx_cpp_mlx_conv_transpose3d`, input_xp_, weight_xp_, stride, padding, dilation, output_padding, groups, device_str)
}

cpp_mlx_quantized_matmul <- function(x_xp_, w_xp_, scales_xp_, biases_xp_, transpose, group_size, bits, mode, device_str) {
    .Call(`_Rmlx_cpp_mlx_quantized_matmul`, x_xp_, w_xp_, scales_xp_, biases_xp_, transpose, group_size, bits, mode, device_str)
}

cpp_mlx_gather_qmm <- function(x_xp_, w_xp_, scales_xp_, biases_xp_, lhs_indices_xp_, rhs_indices_xp_, transpose, group_size, bits, mode, sorted_indices, device_str) {
    .Call(`_Rmlx_cpp_mlx_gather_qmm`, x_xp_, w_xp_, scales_xp_, biases_xp_, lhs_indices_xp_, rhs_indices_xp_, transpose, group_size, bits, mode, sorted_indices, device_str)
}

cpp_mlx_quantize <- function(w_xp_, group_size, bits, mode, device_str) {
    .Call(`_Rmlx_cpp_mlx_quantize`, w_xp_, group_size, bits, mode, device_str)
}

cpp_mlx_dequantize <- function(w_xp_, scales_xp_, biases_xp_, group_size, bits, mode, device_str) {
    .Call(`_Rmlx_cpp_mlx_dequantize`, w_xp_, scales_xp_, biases_xp_, group_size, bits, mode, device_str)
}

cpp_mlx_matmul <- function(xp1_, xp2_, dtype_str, device_str) {
    .Call(`_Rmlx_cpp_mlx_matmul`, xp1_, xp2_, dtype_str, device_str)
}

cpp_mlx_addmm <- function(input_xp_, mat1_xp_, mat2_xp_, alpha, beta, dtype_str, device_str) {
    .Call(`_Rmlx_cpp_mlx_addmm`, input_xp_, mat1_xp_, mat2_xp_, alpha, beta, dtype_str, device_str)
}

cpp_mlx_hadamard_transform <- function(xp_, scale_, device_str) {
    .Call(`_Rmlx_cpp_mlx_hadamard_transform`, xp_, scale_, device_str)
}

cpp_mlx_cast <- function(xp_, dtype_str, device_str) {
    .Call(`_Rmlx_cpp_mlx_cast`, xp_, dtype_str, device_str)
}

cpp_mlx_cumulative <- function(xp_, op) {
    .Call(`_Rmlx_cpp_mlx_cumulative`, xp_, op)
}

cpp_mlx_fft <- function(xp_, axes_, inverse, device_str) {
    .Call(`_Rmlx_cpp_mlx_fft`, xp_, axes_, inverse, device_str)
}

cpp_mlx_cumsum <- function(xp_, axis_, reverse, inclusive) {
    .Call(`_Rmlx_cpp_mlx_cumsum`, xp_, axis_, reverse, inclusive)
}

cpp_mlx_cumprod <- function(xp_, axis_, reverse, inclusive) {
    .Call(`_Rmlx_cpp_mlx_cumprod`, xp_, axis_, reverse, inclusive)
}

cpp_mlx_synchronize <- function(device_str) {
    invisible(.Call(`_Rmlx_cpp_mlx_synchronize`, device_str))
}

cpp_mlx_tril <- function(xp_, k, device_str) {
    .Call(`_Rmlx_cpp_mlx_tril`, xp_, k, device_str)
}

cpp_mlx_triu <- function(xp_, k, device_str) {
    .Call(`_Rmlx_cpp_mlx_triu`, xp_, k, device_str)
}

cpp_mlx_random_key <- function(seed) {
    .Call(`_Rmlx_cpp_mlx_random_key`, seed)
}

cpp_mlx_random_split <- function(key_xp_, num) {
    .Call(`_Rmlx_cpp_mlx_random_split`, key_xp_, num)
}

cpp_mlx_random_bits <- function(dim_, width, key_xp_, device_str) {
    .Call(`_Rmlx_cpp_mlx_random_bits`, dim_, width, key_xp_, device_str)
}

cpp_mlx_random_normal <- function(dim_, mean, std, dtype_str, device_str) {
    .Call(`_Rmlx_cpp_mlx_random_normal`, dim_, mean, std, dtype_str, device_str)
}

cpp_mlx_random_uniform <- function(dim_, low, high, dtype_str, device_str) {
    .Call(`_Rmlx_cpp_mlx_random_uniform`, dim_, low, high, dtype_str, device_str)
}

cpp_mlx_random_bernoulli <- function(dim_, prob, device_str) {
    .Call(`_Rmlx_cpp_mlx_random_bernoulli`, dim_, prob, device_str)
}

cpp_mlx_random_gumbel <- function(dim_, dtype_str, device_str) {
    .Call(`_Rmlx_cpp_mlx_random_gumbel`, dim_, dtype_str, device_str)
}

cpp_mlx_random_truncated_normal <- function(lower_, upper_, dim_, dtype_str, device_str) {
    .Call(`_Rmlx_cpp_mlx_random_truncated_normal`, lower_, upper_, dim_, dtype_str, device_str)
}

cpp_mlx_random_multivariate_normal <- function(mean_, cov_, dim_, dtype_str, device_str) {
    .Call(`_Rmlx_cpp_mlx_random_multivariate_normal`, mean_, cov_, dim_, dtype_str, device_str)
}

cpp_mlx_random_laplace <- function(dim_, loc, scale, dtype_str, device_str) {
    .Call(`_Rmlx_cpp_mlx_random_laplace`, dim_, loc, scale, dtype_str, device_str)
}

cpp_mlx_random_categorical <- function(logits_, axis, num_samples) {
    .Call(`_Rmlx_cpp_mlx_random_categorical`, logits_, axis, num_samples)
}

cpp_mlx_random_randint <- function(dim_, low, high, dtype_str, device_str) {
    .Call(`_Rmlx_cpp_mlx_random_randint`, dim_, low, high, dtype_str, device_str)
}

cpp_mlx_random_permutation_n <- function(n, device_str) {
    .Call(`_Rmlx_cpp_mlx_random_permutation_n`, n, device_str)
}

cpp_mlx_random_permutation <- function(x_, axis) {
    .Call(`_Rmlx_cpp_mlx_random_permutation`, x_, axis)
}

cpp_mlx_reduce <- function(xp_, op, ddof) {
    .Call(`_Rmlx_cpp_mlx_reduce`, xp_, op, ddof)
}

cpp_mlx_reduce_axis <- function(xp_, op, axis, keepdims, ddof) {
    .Call(`_Rmlx_cpp_mlx_reduce_axis`, xp_, op, axis, keepdims, ddof)
}

cpp_mlx_argmax <- function(xp_, axis, keepdims) {
    .Call(`_Rmlx_cpp_mlx_argmax`, xp_, axis, keepdims)
}

cpp_mlx_argmin <- function(xp_, axis, keepdims) {
    .Call(`_Rmlx_cpp_mlx_argmin`, xp_, axis, keepdims)
}

cpp_mlx_logsumexp <- function(xp_, axes, keepdims) {
    .Call(`_Rmlx_cpp_mlx_logsumexp`, xp_, axes, keepdims)
}

cpp_mlx_logsumexp_axis <- function(xp_, axis, keepdims) {
    .Call(`_Rmlx_cpp_mlx_logsumexp_axis`, xp_, axis, keepdims)
}

cpp_mlx_logcumsumexp <- function(xp_, axis, reverse, inclusive) {
    .Call(`_Rmlx_cpp_mlx_logcumsumexp`, xp_, axis, reverse, inclusive)
}

cpp_mlx_softmax <- function(xp_, axes, precise) {
    .Call(`_Rmlx_cpp_mlx_softmax`, xp_, axes, precise)
}

cpp_mlx_softmax_axis <- function(xp_, axis, precise) {
    .Call(`_Rmlx_cpp_mlx_softmax_axis`, xp_, axis, precise)
}

cpp_mlx_transpose <- function(xp_) {
    .Call(`_Rmlx_cpp_mlx_transpose`, xp_)
}

cpp_mlx_reshape <- function(xp_, new_dim_) {
    .Call(`_Rmlx_cpp_mlx_reshape`, xp_, new_dim_)
}

cpp_mlx_concat <- function(args_, axis) {
    .Call(`_Rmlx_cpp_mlx_concat`, args_, axis)
}

cpp_mlx_stack <- function(args_, axis, device_str) {
    .Call(`_Rmlx_cpp_mlx_stack`, args_, axis, device_str)
}

cpp_mlx_squeeze <- function(xp_, axes) {
    .Call(`_Rmlx_cpp_mlx_squeeze`, xp_, axes)
}

cpp_mlx_expand_dims <- function(xp_, axes_) {
    .Call(`_Rmlx_cpp_mlx_expand_dims`, xp_, axes_)
}

cpp_mlx_repeat <- function(xp_, repeats, axis) {
    .Call(`_Rmlx_cpp_mlx_repeat`, xp_, repeats, axis)
}

cpp_mlx_tile <- function(xp_, reps_) {
    .Call(`_Rmlx_cpp_mlx_tile`, xp_, reps_)
}

cpp_mlx_roll <- function(xp_, shift_, axes_) {
    .Call(`_Rmlx_cpp_mlx_roll`, xp_, shift_, axes_)
}

cpp_mlx_moveaxis <- function(xp_, source_, destination_) {
    .Call(`_Rmlx_cpp_mlx_moveaxis`, xp_, source_, destination_)
}

cpp_mlx_flatten <- function(xp_, start_axis, end_axis) {
    .Call(`_Rmlx_cpp_mlx_flatten`, xp_, start_axis, end_axis)
}

cpp_mlx_swapaxes <- function(xp_, axis1, axis2) {
    .Call(`_Rmlx_cpp_mlx_swapaxes`, xp_, axis1, axis2)
}

cpp_mlx_meshgrid <- function(args_, sparse, indexing, device_str) {
    .Call(`_Rmlx_cpp_mlx_meshgrid`, args_, sparse, indexing, device_str)
}

cpp_mlx_broadcast_to <- function(xp_, shape_, device_str) {
    .Call(`_Rmlx_cpp_mlx_broadcast_to`, xp_, shape_, device_str)
}

cpp_mlx_broadcast_arrays <- function(args_, device_str) {
    .Call(`_Rmlx_cpp_mlx_broadcast_arrays`, args_, device_str)
}

cpp_mlx_pad <- function(xp_, pad_pairs_, pad_value, dtype_str, device_str, mode_str) {
    .Call(`_Rmlx_cpp_mlx_pad`, xp_, pad_pairs_, pad_value, dtype_str, device_str, mode_str)
}

cpp_mlx_split <- function(xp_, num_splits_, indices_, axis, dtype_str, device_str) {
    .Call(`_Rmlx_cpp_mlx_split`, xp_, num_splits_, indices_, axis, dtype_str, device_str)
}

cpp_mlx_unflatten <- function(a_xp_, axis, shape, device_str) {
    .Call(`_Rmlx_cpp_mlx_unflatten`, a_xp_, axis, shape, device_str)
}

cpp_mlx_contiguous <- function(xp_, device_str) {
    .Call(`_Rmlx_cpp_mlx_contiguous`, xp_, device_str)
}

cpp_mlx_sort <- function(xp_, axis) {
    .Call(`_Rmlx_cpp_mlx_sort`, xp_, axis)
}

cpp_mlx_argsort <- function(xp_, axis) {
    .Call(`_Rmlx_cpp_mlx_argsort`, xp_, axis)
}

cpp_mlx_topk <- function(xp_, k, axis) {
    .Call(`_Rmlx_cpp_mlx_topk`, xp_, k, axis)
}

cpp_mlx_partition <- function(xp_, kth, axis) {
    .Call(`_Rmlx_cpp_mlx_partition`, xp_, kth, axis)
}

cpp_mlx_argpartition <- function(xp_, kth, axis) {
    .Call(`_Rmlx_cpp_mlx_argpartition`, xp_, kth, axis)
}

cpp_mlx_stream_new <- function(device_str) {
    .Call(`_Rmlx_cpp_mlx_stream_new`, device_str)
}

cpp_mlx_stream_default <- function(device_str) {
    .Call(`_Rmlx_cpp_mlx_stream_default`, device_str)
}

cpp_mlx_set_default_stream <- function(stream_xp) {
    invisible(.Call(`_Rmlx_cpp_mlx_set_default_stream`, stream_xp))
}

cpp_mlx_stream_device <- function(stream_xp) {
    .Call(`_Rmlx_cpp_mlx_stream_device`, stream_xp)
}

cpp_mlx_stream_index <- function(stream_xp) {
    .Call(`_Rmlx_cpp_mlx_stream_index`, stream_xp)
}

cpp_mlx_synchronize_stream <- function(stream_xp) {
    invisible(.Call(`_Rmlx_cpp_mlx_synchronize_stream`, stream_xp))
}

