# Workflow for testing package installation on Linux
# Tests CPU-only build (no CUDA required for CI)

name: Linux Install

on:
  push:
    branches: [experiment-vendor-mlx]
  pull_request:
    branches: [experiment-vendor-mlx]
  workflow_dispatch:

jobs:
  linux-cpu:
    runs-on: ubuntu-latest

    name: Linux CPU-only

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          use-public-rspm: true

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake libblas-dev liblapack-dev liblapacke-dev
          cmake --version

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - name: Build and install package
        run: |
          chmod +x configure cleanup
          R CMD build --no-build-vignettes .
          R CMD INSTALL *.tar.gz --configure-args="--cpu-only"
        shell: bash

      - name: Verify installation
        run: |
          Rscript -e "library(Rmlx); print('Package loaded successfully')"
